import sys
from tkinter import *
from tkinter import messagebox

app = [[1 for j in range(28)] for i in range(28)]
testArray = [[1 for j in range(28)] for i in range(28)]
buttonPress = False
buttonRelease = False

class drawNumber:
    def showBoard(self):
        global buttonRelease, buttonPress, app

        root = Tk()
        root.resizable(0, 0)
        root.protocol('WM_DELETE_WINDOW', lambda: sys.exit())
        root.bind('<Return>', lambda event: root.destroy())
        root.bind('<space>', lambda event: self.clearBoard(app))
        root.title('Draw any Number :-')

        for i in range(28):
            for j in range(28):
                app[i][j] = Label(root, text="", bg='#000', font=('Verdana', 12), width=2, height=1)
                app[i][j].grid(row=i, column=j, padx=0, pady=0, columnspan=1)
                app[i][j].bind('<Button-1>', lambda event: self.draw(event))
                app[i][j].bind('<Button-3>', lambda event: self.clearBoard(app))
                app[i][j].bind('<ButtonRelease-1>', lambda event: self.endDraw(event, root))

        app[0][0].bind('<Motion>', lambda event: self.drawMotion(event, 0, 0))
        app[0][1].bind('<Motion>', lambda event: self.drawMotion(event, 0, 1))
        app[0][2].bind('<Motion>', lambda event: self.drawMotion(event, 0, 2))
        app[0][3].bind('<Motion>', lambda event: self.drawMotion(event, 0, 3))
        app[0][4].bind('<Motion>', lambda event: self.drawMotion(event, 0, 4))
        app[0][5].bind('<Motion>', lambda event: self.drawMotion(event, 0, 5))
        app[0][6].bind('<Motion>', lambda event: self.drawMotion(event, 0, 6))
        app[0][7].bind('<Motion>', lambda event: self.drawMotion(event, 0, 7))
        app[0][8].bind('<Motion>', lambda event: self.drawMotion(event, 0, 8))
        app[0][9].bind('<Motion>', lambda event: self.drawMotion(event, 0, 9))
        app[0][10].bind('<Motion>', lambda event: self.drawMotion(event, 0, 10))
        app[0][11].bind('<Motion>', lambda event: self.drawMotion(event, 0, 11))
        app[0][12].bind('<Motion>', lambda event: self.drawMotion(event, 0, 12))
        app[0][13].bind('<Motion>', lambda event: self.drawMotion(event, 0, 13))
        app[0][14].bind('<Motion>', lambda event: self.drawMotion(event, 0, 14))
        app[0][15].bind('<Motion>', lambda event: self.drawMotion(event, 0, 15))
        app[0][16].bind('<Motion>', lambda event: self.drawMotion(event, 0, 16))
        app[0][17].bind('<Motion>', lambda event: self.drawMotion(event, 0, 17))
        app[0][18].bind('<Motion>', lambda event: self.drawMotion(event, 0, 18))
        app[0][19].bind('<Motion>', lambda event: self.drawMotion(event, 0, 19))
        app[0][20].bind('<Motion>', lambda event: self.drawMotion(event, 0, 20))
        app[0][21].bind('<Motion>', lambda event: self.drawMotion(event, 0, 21))
        app[0][22].bind('<Motion>', lambda event: self.drawMotion(event, 0, 22))
        app[0][23].bind('<Motion>', lambda event: self.drawMotion(event, 0, 23))
        app[0][24].bind('<Motion>', lambda event: self.drawMotion(event, 0, 24))
        app[0][25].bind('<Motion>', lambda event: self.drawMotion(event, 0, 25))
        app[0][26].bind('<Motion>', lambda event: self.drawMotion(event, 0, 26))
        app[0][27].bind('<Motion>', lambda event: self.drawMotion(event, 0, 27))

        app[1][0].bind('<Motion>', lambda event: self.drawMotion(event, 1, 0))
        app[1][1].bind('<Motion>', lambda event: self.drawMotion(event, 1, 1))
        app[1][2].bind('<Motion>', lambda event: self.drawMotion(event, 1, 2))
        app[1][3].bind('<Motion>', lambda event: self.drawMotion(event, 1, 3))
        app[1][4].bind('<Motion>', lambda event: self.drawMotion(event, 1, 4))
        app[1][5].bind('<Motion>', lambda event: self.drawMotion(event, 1, 5))
        app[1][6].bind('<Motion>', lambda event: self.drawMotion(event, 1, 6))
        app[1][7].bind('<Motion>', lambda event: self.drawMotion(event, 1, 7))
        app[1][8].bind('<Motion>', lambda event: self.drawMotion(event, 1, 8))
        app[1][9].bind('<Motion>', lambda event: self.drawMotion(event, 1, 9))
        app[1][10].bind('<Motion>', lambda event: self.drawMotion(event, 1, 10))
        app[1][11].bind('<Motion>', lambda event: self.drawMotion(event, 1, 11))
        app[1][12].bind('<Motion>', lambda event: self.drawMotion(event, 1, 12))
        app[1][13].bind('<Motion>', lambda event: self.drawMotion(event, 1, 13))
        app[1][14].bind('<Motion>', lambda event: self.drawMotion(event, 1, 14))
        app[1][15].bind('<Motion>', lambda event: self.drawMotion(event, 1, 15))
        app[1][16].bind('<Motion>', lambda event: self.drawMotion(event, 1, 16))
        app[1][17].bind('<Motion>', lambda event: self.drawMotion(event, 1, 17))
        app[1][18].bind('<Motion>', lambda event: self.drawMotion(event, 1, 18))
        app[1][19].bind('<Motion>', lambda event: self.drawMotion(event, 1, 19))
        app[1][20].bind('<Motion>', lambda event: self.drawMotion(event, 1, 20))
        app[1][21].bind('<Motion>', lambda event: self.drawMotion(event, 1, 21))
        app[1][22].bind('<Motion>', lambda event: self.drawMotion(event, 1, 22))
        app[1][23].bind('<Motion>', lambda event: self.drawMotion(event, 1, 23))
        app[1][24].bind('<Motion>', lambda event: self.drawMotion(event, 1, 24))
        app[1][25].bind('<Motion>', lambda event: self.drawMotion(event, 1, 25))
        app[1][26].bind('<Motion>', lambda event: self.drawMotion(event, 1, 26))
        app[1][27].bind('<Motion>', lambda event: self.drawMotion(event, 1, 27))

        app[2][0].bind('<Motion>', lambda event: self.drawMotion(event, 2, 0))
        app[2][1].bind('<Motion>', lambda event: self.drawMotion(event, 2, 1))
        app[2][2].bind('<Motion>', lambda event: self.drawMotion(event, 2, 2))
        app[2][3].bind('<Motion>', lambda event: self.drawMotion(event, 2, 3))
        app[2][4].bind('<Motion>', lambda event: self.drawMotion(event, 2, 4))
        app[2][5].bind('<Motion>', lambda event: self.drawMotion(event, 2, 5))
        app[2][6].bind('<Motion>', lambda event: self.drawMotion(event, 2, 6))
        app[2][7].bind('<Motion>', lambda event: self.drawMotion(event, 2, 7))
        app[2][8].bind('<Motion>', lambda event: self.drawMotion(event, 2, 8))
        app[2][9].bind('<Motion>', lambda event: self.drawMotion(event, 2, 9))
        app[2][10].bind('<Motion>', lambda event: self.drawMotion(event, 2, 10))
        app[2][11].bind('<Motion>', lambda event: self.drawMotion(event, 2, 11))
        app[2][12].bind('<Motion>', lambda event: self.drawMotion(event, 2, 12))
        app[2][13].bind('<Motion>', lambda event: self.drawMotion(event, 2, 13))
        app[2][14].bind('<Motion>', lambda event: self.drawMotion(event, 2, 14))
        app[2][15].bind('<Motion>', lambda event: self.drawMotion(event, 2, 15))
        app[2][16].bind('<Motion>', lambda event: self.drawMotion(event, 2, 16))
        app[2][17].bind('<Motion>', lambda event: self.drawMotion(event, 2, 17))
        app[2][18].bind('<Motion>', lambda event: self.drawMotion(event, 2, 18))
        app[2][19].bind('<Motion>', lambda event: self.drawMotion(event, 2, 19))
        app[2][20].bind('<Motion>', lambda event: self.drawMotion(event, 2, 20))
        app[2][21].bind('<Motion>', lambda event: self.drawMotion(event, 2, 21))
        app[2][22].bind('<Motion>', lambda event: self.drawMotion(event, 2, 22))
        app[2][23].bind('<Motion>', lambda event: self.drawMotion(event, 2, 23))
        app[2][24].bind('<Motion>', lambda event: self.drawMotion(event, 2, 24))
        app[2][25].bind('<Motion>', lambda event: self.drawMotion(event, 2, 25))
        app[2][26].bind('<Motion>', lambda event: self.drawMotion(event, 2, 26))
        app[2][27].bind('<Motion>', lambda event: self.drawMotion(event, 2, 27))

        app[3][0].bind('<Motion>', lambda event: self.drawMotion(event, 3, 0))
        app[3][1].bind('<Motion>', lambda event: self.drawMotion(event, 3, 1))
        app[3][2].bind('<Motion>', lambda event: self.drawMotion(event, 3, 2))
        app[3][3].bind('<Motion>', lambda event: self.drawMotion(event, 3, 3))
        app[3][4].bind('<Motion>', lambda event: self.drawMotion(event, 3, 4))
        app[3][5].bind('<Motion>', lambda event: self.drawMotion(event, 3, 5))
        app[3][6].bind('<Motion>', lambda event: self.drawMotion(event, 3, 6))
        app[3][7].bind('<Motion>', lambda event: self.drawMotion(event, 3, 7))
        app[3][8].bind('<Motion>', lambda event: self.drawMotion(event, 3, 8))
        app[3][9].bind('<Motion>', lambda event: self.drawMotion(event, 3, 9))
        app[3][10].bind('<Motion>', lambda event: self.drawMotion(event, 3, 10))
        app[3][11].bind('<Motion>', lambda event: self.drawMotion(event, 3, 11))
        app[3][12].bind('<Motion>', lambda event: self.drawMotion(event, 3, 12))
        app[3][13].bind('<Motion>', lambda event: self.drawMotion(event, 3, 13))
        app[3][14].bind('<Motion>', lambda event: self.drawMotion(event, 3, 14))
        app[3][15].bind('<Motion>', lambda event: self.drawMotion(event, 3, 15))
        app[3][16].bind('<Motion>', lambda event: self.drawMotion(event, 3, 16))
        app[3][17].bind('<Motion>', lambda event: self.drawMotion(event, 3, 17))
        app[3][18].bind('<Motion>', lambda event: self.drawMotion(event, 3, 18))
        app[3][19].bind('<Motion>', lambda event: self.drawMotion(event, 3, 19))
        app[3][20].bind('<Motion>', lambda event: self.drawMotion(event, 3, 20))
        app[3][21].bind('<Motion>', lambda event: self.drawMotion(event, 3, 21))
        app[3][22].bind('<Motion>', lambda event: self.drawMotion(event, 3, 22))
        app[3][23].bind('<Motion>', lambda event: self.drawMotion(event, 3, 23))
        app[3][24].bind('<Motion>', lambda event: self.drawMotion(event, 3, 24))
        app[3][25].bind('<Motion>', lambda event: self.drawMotion(event, 3, 25))
        app[3][26].bind('<Motion>', lambda event: self.drawMotion(event, 3, 26))
        app[3][27].bind('<Motion>', lambda event: self.drawMotion(event, 3, 27))

        app[4][0].bind('<Motion>', lambda event: self.drawMotion(event, 4, 0))
        app[4][1].bind('<Motion>', lambda event: self.drawMotion(event, 4, 1))
        app[4][2].bind('<Motion>', lambda event: self.drawMotion(event, 4, 2))
        app[4][3].bind('<Motion>', lambda event: self.drawMotion(event, 4, 3))
        app[4][4].bind('<Motion>', lambda event: self.drawMotion(event, 4, 4))
        app[4][5].bind('<Motion>', lambda event: self.drawMotion(event, 4, 5))
        app[4][6].bind('<Motion>', lambda event: self.drawMotion(event, 4, 6))
        app[4][7].bind('<Motion>', lambda event: self.drawMotion(event, 4, 7))
        app[4][8].bind('<Motion>', lambda event: self.drawMotion(event, 4, 8))
        app[4][9].bind('<Motion>', lambda event: self.drawMotion(event, 4, 9))
        app[4][10].bind('<Motion>', lambda event: self.drawMotion(event, 4, 10))
        app[4][11].bind('<Motion>', lambda event: self.drawMotion(event, 4, 11))
        app[4][12].bind('<Motion>', lambda event: self.drawMotion(event, 4, 12))
        app[4][13].bind('<Motion>', lambda event: self.drawMotion(event, 4, 13))
        app[4][14].bind('<Motion>', lambda event: self.drawMotion(event, 4, 14))
        app[4][15].bind('<Motion>', lambda event: self.drawMotion(event, 4, 15))
        app[4][16].bind('<Motion>', lambda event: self.drawMotion(event, 4, 16))
        app[4][17].bind('<Motion>', lambda event: self.drawMotion(event, 4, 17))
        app[4][18].bind('<Motion>', lambda event: self.drawMotion(event, 4, 18))
        app[4][19].bind('<Motion>', lambda event: self.drawMotion(event, 4, 19))
        app[4][20].bind('<Motion>', lambda event: self.drawMotion(event, 4, 20))
        app[4][21].bind('<Motion>', lambda event: self.drawMotion(event, 4, 21))
        app[4][22].bind('<Motion>', lambda event: self.drawMotion(event, 4, 22))
        app[4][23].bind('<Motion>', lambda event: self.drawMotion(event, 4, 23))
        app[4][24].bind('<Motion>', lambda event: self.drawMotion(event, 4, 24))
        app[4][25].bind('<Motion>', lambda event: self.drawMotion(event, 4, 25))
        app[4][26].bind('<Motion>', lambda event: self.drawMotion(event, 4, 26))
        app[4][27].bind('<Motion>', lambda event: self.drawMotion(event, 4, 27))

        app[5][0].bind('<Motion>', lambda event: self.drawMotion(event, 5, 0))
        app[5][1].bind('<Motion>', lambda event: self.drawMotion(event, 5, 1))
        app[5][2].bind('<Motion>', lambda event: self.drawMotion(event, 5, 2))
        app[5][3].bind('<Motion>', lambda event: self.drawMotion(event, 5, 3))
        app[5][4].bind('<Motion>', lambda event: self.drawMotion(event, 5, 4))
        app[5][5].bind('<Motion>', lambda event: self.drawMotion(event, 5, 5))
        app[5][6].bind('<Motion>', lambda event: self.drawMotion(event, 5, 6))
        app[5][7].bind('<Motion>', lambda event: self.drawMotion(event, 5, 7))
        app[5][8].bind('<Motion>', lambda event: self.drawMotion(event, 5, 8))
        app[5][9].bind('<Motion>', lambda event: self.drawMotion(event, 5, 9))
        app[5][10].bind('<Motion>', lambda event: self.drawMotion(event, 5, 10))
        app[5][11].bind('<Motion>', lambda event: self.drawMotion(event, 5, 11))
        app[5][12].bind('<Motion>', lambda event: self.drawMotion(event, 5, 12))
        app[5][13].bind('<Motion>', lambda event: self.drawMotion(event, 5, 13))
        app[5][14].bind('<Motion>', lambda event: self.drawMotion(event, 5, 14))
        app[5][15].bind('<Motion>', lambda event: self.drawMotion(event, 5, 15))
        app[5][16].bind('<Motion>', lambda event: self.drawMotion(event, 5, 16))
        app[5][17].bind('<Motion>', lambda event: self.drawMotion(event, 5, 17))
        app[5][18].bind('<Motion>', lambda event: self.drawMotion(event, 5, 18))
        app[5][19].bind('<Motion>', lambda event: self.drawMotion(event, 5, 19))
        app[5][20].bind('<Motion>', lambda event: self.drawMotion(event, 5, 20))
        app[5][21].bind('<Motion>', lambda event: self.drawMotion(event, 5, 21))
        app[5][22].bind('<Motion>', lambda event: self.drawMotion(event, 5, 22))
        app[5][23].bind('<Motion>', lambda event: self.drawMotion(event, 5, 23))
        app[5][24].bind('<Motion>', lambda event: self.drawMotion(event, 5, 24))
        app[5][25].bind('<Motion>', lambda event: self.drawMotion(event, 5, 25))
        app[5][26].bind('<Motion>', lambda event: self.drawMotion(event, 5, 26))
        app[5][27].bind('<Motion>', lambda event: self.drawMotion(event, 5, 27))

        app[6][0].bind('<Motion>', lambda event: self.drawMotion(event, 6, 0))
        app[6][1].bind('<Motion>', lambda event: self.drawMotion(event, 6, 1))
        app[6][2].bind('<Motion>', lambda event: self.drawMotion(event, 6, 2))
        app[6][3].bind('<Motion>', lambda event: self.drawMotion(event, 6, 3))
        app[6][4].bind('<Motion>', lambda event: self.drawMotion(event, 6, 4))
        app[6][5].bind('<Motion>', lambda event: self.drawMotion(event, 6, 5))
        app[6][6].bind('<Motion>', lambda event: self.drawMotion(event, 6, 6))
        app[6][7].bind('<Motion>', lambda event: self.drawMotion(event, 6, 7))
        app[6][8].bind('<Motion>', lambda event: self.drawMotion(event, 6, 8))
        app[6][9].bind('<Motion>', lambda event: self.drawMotion(event, 6, 9))
        app[6][10].bind('<Motion>', lambda event: self.drawMotion(event, 6, 10))
        app[6][11].bind('<Motion>', lambda event: self.drawMotion(event, 6, 11))
        app[6][12].bind('<Motion>', lambda event: self.drawMotion(event, 6, 12))
        app[6][13].bind('<Motion>', lambda event: self.drawMotion(event, 6, 13))
        app[6][14].bind('<Motion>', lambda event: self.drawMotion(event, 6, 14))
        app[6][15].bind('<Motion>', lambda event: self.drawMotion(event, 6, 15))
        app[6][16].bind('<Motion>', lambda event: self.drawMotion(event, 6, 16))
        app[6][17].bind('<Motion>', lambda event: self.drawMotion(event, 6, 17))
        app[6][18].bind('<Motion>', lambda event: self.drawMotion(event, 6, 18))
        app[6][19].bind('<Motion>', lambda event: self.drawMotion(event, 6, 19))
        app[6][20].bind('<Motion>', lambda event: self.drawMotion(event, 6, 20))
        app[6][21].bind('<Motion>', lambda event: self.drawMotion(event, 6, 21))
        app[6][22].bind('<Motion>', lambda event: self.drawMotion(event, 6, 22))
        app[6][23].bind('<Motion>', lambda event: self.drawMotion(event, 6, 23))
        app[6][24].bind('<Motion>', lambda event: self.drawMotion(event, 6, 24))
        app[6][25].bind('<Motion>', lambda event: self.drawMotion(event, 6, 25))
        app[6][26].bind('<Motion>', lambda event: self.drawMotion(event, 6, 26))
        app[6][27].bind('<Motion>', lambda event: self.drawMotion(event, 6, 27))

        app[7][0].bind('<Motion>', lambda event: self.drawMotion(event, 7, 0))
        app[7][1].bind('<Motion>', lambda event: self.drawMotion(event, 7, 1))
        app[7][2].bind('<Motion>', lambda event: self.drawMotion(event, 7, 2))
        app[7][3].bind('<Motion>', lambda event: self.drawMotion(event, 7, 3))
        app[7][4].bind('<Motion>', lambda event: self.drawMotion(event, 7, 4))
        app[7][5].bind('<Motion>', lambda event: self.drawMotion(event, 7, 5))
        app[7][6].bind('<Motion>', lambda event: self.drawMotion(event, 7, 6))
        app[7][7].bind('<Motion>', lambda event: self.drawMotion(event, 7, 7))
        app[7][8].bind('<Motion>', lambda event: self.drawMotion(event, 7, 8))
        app[7][9].bind('<Motion>', lambda event: self.drawMotion(event, 7, 9))
        app[7][10].bind('<Motion>', lambda event: self.drawMotion(event, 7, 10))
        app[7][11].bind('<Motion>', lambda event: self.drawMotion(event, 7, 11))
        app[7][12].bind('<Motion>', lambda event: self.drawMotion(event, 7, 12))
        app[7][13].bind('<Motion>', lambda event: self.drawMotion(event, 7, 13))
        app[7][14].bind('<Motion>', lambda event: self.drawMotion(event, 7, 14))
        app[7][15].bind('<Motion>', lambda event: self.drawMotion(event, 7, 15))
        app[7][16].bind('<Motion>', lambda event: self.drawMotion(event, 7, 16))
        app[7][17].bind('<Motion>', lambda event: self.drawMotion(event, 7, 17))
        app[7][18].bind('<Motion>', lambda event: self.drawMotion(event, 7, 18))
        app[7][19].bind('<Motion>', lambda event: self.drawMotion(event, 7, 19))
        app[7][20].bind('<Motion>', lambda event: self.drawMotion(event, 7, 20))
        app[7][21].bind('<Motion>', lambda event: self.drawMotion(event, 7, 21))
        app[7][22].bind('<Motion>', lambda event: self.drawMotion(event, 7, 22))
        app[7][23].bind('<Motion>', lambda event: self.drawMotion(event, 7, 23))
        app[7][24].bind('<Motion>', lambda event: self.drawMotion(event, 7, 24))
        app[7][25].bind('<Motion>', lambda event: self.drawMotion(event, 7, 25))
        app[7][26].bind('<Motion>', lambda event: self.drawMotion(event, 7, 26))
        app[7][27].bind('<Motion>', lambda event: self.drawMotion(event, 7, 27))

        app[8][0].bind('<Motion>', lambda event: self.drawMotion(event, 8, 0))
        app[8][1].bind('<Motion>', lambda event: self.drawMotion(event, 8, 1))
        app[8][2].bind('<Motion>', lambda event: self.drawMotion(event, 8, 2))
        app[8][3].bind('<Motion>', lambda event: self.drawMotion(event, 8, 3))
        app[8][4].bind('<Motion>', lambda event: self.drawMotion(event, 8, 4))
        app[8][5].bind('<Motion>', lambda event: self.drawMotion(event, 8, 5))
        app[8][6].bind('<Motion>', lambda event: self.drawMotion(event, 8, 6))
        app[8][7].bind('<Motion>', lambda event: self.drawMotion(event, 8, 7))
        app[8][8].bind('<Motion>', lambda event: self.drawMotion(event, 8, 8))
        app[8][9].bind('<Motion>', lambda event: self.drawMotion(event, 8, 9))
        app[8][10].bind('<Motion>', lambda event: self.drawMotion(event, 8, 10))
        app[8][11].bind('<Motion>', lambda event: self.drawMotion(event, 8, 11))
        app[8][12].bind('<Motion>', lambda event: self.drawMotion(event, 8, 12))
        app[8][13].bind('<Motion>', lambda event: self.drawMotion(event, 8, 13))
        app[8][14].bind('<Motion>', lambda event: self.drawMotion(event, 8, 14))
        app[8][15].bind('<Motion>', lambda event: self.drawMotion(event, 8, 15))
        app[8][16].bind('<Motion>', lambda event: self.drawMotion(event, 8, 16))
        app[8][17].bind('<Motion>', lambda event: self.drawMotion(event, 8, 17))
        app[8][18].bind('<Motion>', lambda event: self.drawMotion(event, 8, 18))
        app[8][19].bind('<Motion>', lambda event: self.drawMotion(event, 8, 19))
        app[8][20].bind('<Motion>', lambda event: self.drawMotion(event, 8, 20))
        app[8][21].bind('<Motion>', lambda event: self.drawMotion(event, 8, 21))
        app[8][22].bind('<Motion>', lambda event: self.drawMotion(event, 8, 22))
        app[8][23].bind('<Motion>', lambda event: self.drawMotion(event, 8, 23))
        app[8][24].bind('<Motion>', lambda event: self.drawMotion(event, 8, 24))
        app[8][25].bind('<Motion>', lambda event: self.drawMotion(event, 8, 25))
        app[8][26].bind('<Motion>', lambda event: self.drawMotion(event, 8, 26))
        app[8][27].bind('<Motion>', lambda event: self.drawMotion(event, 8, 27))

        app[9][0].bind('<Motion>', lambda event: self.drawMotion(event, 9, 0))
        app[9][1].bind('<Motion>', lambda event: self.drawMotion(event, 9, 1))
        app[9][2].bind('<Motion>', lambda event: self.drawMotion(event, 9, 2))
        app[9][3].bind('<Motion>', lambda event: self.drawMotion(event, 9, 3))
        app[9][4].bind('<Motion>', lambda event: self.drawMotion(event, 9, 4))
        app[9][5].bind('<Motion>', lambda event: self.drawMotion(event, 9, 5))
        app[9][6].bind('<Motion>', lambda event: self.drawMotion(event, 9, 6))
        app[9][7].bind('<Motion>', lambda event: self.drawMotion(event, 9, 7))
        app[9][8].bind('<Motion>', lambda event: self.drawMotion(event, 9, 8))
        app[9][9].bind('<Motion>', lambda event: self.drawMotion(event, 9, 9))
        app[9][10].bind('<Motion>', lambda event: self.drawMotion(event, 9, 10))
        app[9][11].bind('<Motion>', lambda event: self.drawMotion(event, 9, 11))
        app[9][12].bind('<Motion>', lambda event: self.drawMotion(event, 9, 12))
        app[9][13].bind('<Motion>', lambda event: self.drawMotion(event, 9, 13))
        app[9][14].bind('<Motion>', lambda event: self.drawMotion(event, 9, 14))
        app[9][15].bind('<Motion>', lambda event: self.drawMotion(event, 9, 15))
        app[9][16].bind('<Motion>', lambda event: self.drawMotion(event, 9, 16))
        app[9][17].bind('<Motion>', lambda event: self.drawMotion(event, 9, 17))
        app[9][18].bind('<Motion>', lambda event: self.drawMotion(event, 9, 18))
        app[9][19].bind('<Motion>', lambda event: self.drawMotion(event, 9, 19))
        app[9][20].bind('<Motion>', lambda event: self.drawMotion(event, 9, 20))
        app[9][21].bind('<Motion>', lambda event: self.drawMotion(event, 9, 21))
        app[9][22].bind('<Motion>', lambda event: self.drawMotion(event, 9, 22))
        app[9][23].bind('<Motion>', lambda event: self.drawMotion(event, 9, 23))
        app[9][24].bind('<Motion>', lambda event: self.drawMotion(event, 9, 24))
        app[9][25].bind('<Motion>', lambda event: self.drawMotion(event, 9, 25))
        app[9][26].bind('<Motion>', lambda event: self.drawMotion(event, 9, 26))
        app[9][27].bind('<Motion>', lambda event: self.drawMotion(event, 9, 27))

        app[10][0].bind('<Motion>', lambda event: self.drawMotion(event, 10, 0))
        app[10][1].bind('<Motion>', lambda event: self.drawMotion(event, 10, 1))
        app[10][2].bind('<Motion>', lambda event: self.drawMotion(event, 10, 2))
        app[10][3].bind('<Motion>', lambda event: self.drawMotion(event, 10, 3))
        app[10][4].bind('<Motion>', lambda event: self.drawMotion(event, 10, 4))
        app[10][5].bind('<Motion>', lambda event: self.drawMotion(event, 10, 5))
        app[10][6].bind('<Motion>', lambda event: self.drawMotion(event, 10, 6))
        app[10][7].bind('<Motion>', lambda event: self.drawMotion(event, 10, 7))
        app[10][8].bind('<Motion>', lambda event: self.drawMotion(event, 10, 8))
        app[10][9].bind('<Motion>', lambda event: self.drawMotion(event, 10, 9))
        app[10][10].bind('<Motion>', lambda event: self.drawMotion(event, 10, 10))
        app[10][11].bind('<Motion>', lambda event: self.drawMotion(event, 10, 11))
        app[10][12].bind('<Motion>', lambda event: self.drawMotion(event, 10, 12))
        app[10][13].bind('<Motion>', lambda event: self.drawMotion(event, 10, 13))
        app[10][14].bind('<Motion>', lambda event: self.drawMotion(event, 10, 14))
        app[10][15].bind('<Motion>', lambda event: self.drawMotion(event, 10, 15))
        app[10][16].bind('<Motion>', lambda event: self.drawMotion(event, 10, 16))
        app[10][17].bind('<Motion>', lambda event: self.drawMotion(event, 10, 17))
        app[10][18].bind('<Motion>', lambda event: self.drawMotion(event, 10, 18))
        app[10][19].bind('<Motion>', lambda event: self.drawMotion(event, 10, 19))
        app[10][20].bind('<Motion>', lambda event: self.drawMotion(event, 10, 20))
        app[10][21].bind('<Motion>', lambda event: self.drawMotion(event, 10, 21))
        app[10][22].bind('<Motion>', lambda event: self.drawMotion(event, 10, 22))
        app[10][23].bind('<Motion>', lambda event: self.drawMotion(event, 10, 23))
        app[10][24].bind('<Motion>', lambda event: self.drawMotion(event, 10, 24))
        app[10][25].bind('<Motion>', lambda event: self.drawMotion(event, 10, 25))
        app[10][26].bind('<Motion>', lambda event: self.drawMotion(event, 10, 26))
        app[10][27].bind('<Motion>', lambda event: self.drawMotion(event, 10, 27))

        app[11][0].bind('<Motion>', lambda event: self.drawMotion(event, 11, 0))
        app[11][1].bind('<Motion>', lambda event: self.drawMotion(event, 11, 1))
        app[11][2].bind('<Motion>', lambda event: self.drawMotion(event, 11, 2))
        app[11][3].bind('<Motion>', lambda event: self.drawMotion(event, 11, 3))
        app[11][4].bind('<Motion>', lambda event: self.drawMotion(event, 11, 4))
        app[11][5].bind('<Motion>', lambda event: self.drawMotion(event, 11, 5))
        app[11][6].bind('<Motion>', lambda event: self.drawMotion(event, 11, 6))
        app[11][7].bind('<Motion>', lambda event: self.drawMotion(event, 11, 7))
        app[11][8].bind('<Motion>', lambda event: self.drawMotion(event, 11, 8))
        app[11][9].bind('<Motion>', lambda event: self.drawMotion(event, 11, 9))
        app[11][10].bind('<Motion>', lambda event: self.drawMotion(event, 11, 10))
        app[11][11].bind('<Motion>', lambda event: self.drawMotion(event, 11, 11))
        app[11][12].bind('<Motion>', lambda event: self.drawMotion(event, 11, 12))
        app[11][13].bind('<Motion>', lambda event: self.drawMotion(event, 11, 13))
        app[11][14].bind('<Motion>', lambda event: self.drawMotion(event, 11, 14))
        app[11][15].bind('<Motion>', lambda event: self.drawMotion(event, 11, 15))
        app[11][16].bind('<Motion>', lambda event: self.drawMotion(event, 11, 16))
        app[11][17].bind('<Motion>', lambda event: self.drawMotion(event, 11, 17))
        app[11][18].bind('<Motion>', lambda event: self.drawMotion(event, 11, 18))
        app[11][19].bind('<Motion>', lambda event: self.drawMotion(event, 11, 19))
        app[11][20].bind('<Motion>', lambda event: self.drawMotion(event, 11, 20))
        app[11][21].bind('<Motion>', lambda event: self.drawMotion(event, 11, 21))
        app[11][22].bind('<Motion>', lambda event: self.drawMotion(event, 11, 22))
        app[11][23].bind('<Motion>', lambda event: self.drawMotion(event, 11, 23))
        app[11][24].bind('<Motion>', lambda event: self.drawMotion(event, 11, 24))
        app[11][25].bind('<Motion>', lambda event: self.drawMotion(event, 11, 25))
        app[11][26].bind('<Motion>', lambda event: self.drawMotion(event, 11, 26))
        app[11][27].bind('<Motion>', lambda event: self.drawMotion(event, 11, 27))

        app[12][0].bind('<Motion>', lambda event: self.drawMotion(event, 12, 0))
        app[12][1].bind('<Motion>', lambda event: self.drawMotion(event, 12, 1))
        app[12][2].bind('<Motion>', lambda event: self.drawMotion(event, 12, 2))
        app[12][3].bind('<Motion>', lambda event: self.drawMotion(event, 12, 3))
        app[12][4].bind('<Motion>', lambda event: self.drawMotion(event, 12, 4))
        app[12][5].bind('<Motion>', lambda event: self.drawMotion(event, 12, 5))
        app[12][6].bind('<Motion>', lambda event: self.drawMotion(event, 12, 6))
        app[12][7].bind('<Motion>', lambda event: self.drawMotion(event, 12, 7))
        app[12][8].bind('<Motion>', lambda event: self.drawMotion(event, 12, 8))
        app[12][9].bind('<Motion>', lambda event: self.drawMotion(event, 12, 9))
        app[12][10].bind('<Motion>', lambda event: self.drawMotion(event, 12, 10))
        app[12][11].bind('<Motion>', lambda event: self.drawMotion(event, 12, 11))
        app[12][12].bind('<Motion>', lambda event: self.drawMotion(event, 12, 12))
        app[12][13].bind('<Motion>', lambda event: self.drawMotion(event, 12, 13))
        app[12][14].bind('<Motion>', lambda event: self.drawMotion(event, 12, 14))
        app[12][15].bind('<Motion>', lambda event: self.drawMotion(event, 12, 15))
        app[12][16].bind('<Motion>', lambda event: self.drawMotion(event, 12, 16))
        app[12][17].bind('<Motion>', lambda event: self.drawMotion(event, 12, 17))
        app[12][18].bind('<Motion>', lambda event: self.drawMotion(event, 12, 18))
        app[12][19].bind('<Motion>', lambda event: self.drawMotion(event, 12, 19))
        app[12][20].bind('<Motion>', lambda event: self.drawMotion(event, 12, 20))
        app[12][21].bind('<Motion>', lambda event: self.drawMotion(event, 12, 21))
        app[12][22].bind('<Motion>', lambda event: self.drawMotion(event, 12, 22))
        app[12][23].bind('<Motion>', lambda event: self.drawMotion(event, 12, 23))
        app[12][24].bind('<Motion>', lambda event: self.drawMotion(event, 12, 24))
        app[12][25].bind('<Motion>', lambda event: self.drawMotion(event, 12, 25))
        app[12][26].bind('<Motion>', lambda event: self.drawMotion(event, 12, 26))
        app[12][27].bind('<Motion>', lambda event: self.drawMotion(event, 12, 27))

        app[13][0].bind('<Motion>', lambda event: self.drawMotion(event, 13, 0))
        app[13][1].bind('<Motion>', lambda event: self.drawMotion(event, 13, 1))
        app[13][2].bind('<Motion>', lambda event: self.drawMotion(event, 13, 2))
        app[13][3].bind('<Motion>', lambda event: self.drawMotion(event, 13, 3))
        app[13][4].bind('<Motion>', lambda event: self.drawMotion(event, 13, 4))
        app[13][5].bind('<Motion>', lambda event: self.drawMotion(event, 13, 5))
        app[13][6].bind('<Motion>', lambda event: self.drawMotion(event, 13, 6))
        app[13][7].bind('<Motion>', lambda event: self.drawMotion(event, 13, 7))
        app[13][8].bind('<Motion>', lambda event: self.drawMotion(event, 13, 8))
        app[13][9].bind('<Motion>', lambda event: self.drawMotion(event, 13, 9))
        app[13][10].bind('<Motion>', lambda event: self.drawMotion(event, 13, 10))
        app[13][11].bind('<Motion>', lambda event: self.drawMotion(event, 13, 11))
        app[13][12].bind('<Motion>', lambda event: self.drawMotion(event, 13, 12))
        app[13][13].bind('<Motion>', lambda event: self.drawMotion(event, 13, 13))
        app[13][14].bind('<Motion>', lambda event: self.drawMotion(event, 13, 14))
        app[13][15].bind('<Motion>', lambda event: self.drawMotion(event, 13, 15))
        app[13][16].bind('<Motion>', lambda event: self.drawMotion(event, 13, 16))
        app[13][17].bind('<Motion>', lambda event: self.drawMotion(event, 13, 17))
        app[13][18].bind('<Motion>', lambda event: self.drawMotion(event, 13, 18))
        app[13][19].bind('<Motion>', lambda event: self.drawMotion(event, 13, 19))
        app[13][20].bind('<Motion>', lambda event: self.drawMotion(event, 13, 20))
        app[13][21].bind('<Motion>', lambda event: self.drawMotion(event, 13, 21))
        app[13][22].bind('<Motion>', lambda event: self.drawMotion(event, 13, 22))
        app[13][23].bind('<Motion>', lambda event: self.drawMotion(event, 13, 23))
        app[13][24].bind('<Motion>', lambda event: self.drawMotion(event, 13, 24))
        app[13][25].bind('<Motion>', lambda event: self.drawMotion(event, 13, 25))
        app[13][26].bind('<Motion>', lambda event: self.drawMotion(event, 13, 26))
        app[13][27].bind('<Motion>', lambda event: self.drawMotion(event, 13, 27))

        app[14][0].bind('<Motion>', lambda event: self.drawMotion(event, 14, 0))
        app[14][1].bind('<Motion>', lambda event: self.drawMotion(event, 14, 1))
        app[14][2].bind('<Motion>', lambda event: self.drawMotion(event, 14, 2))
        app[14][3].bind('<Motion>', lambda event: self.drawMotion(event, 14, 3))
        app[14][4].bind('<Motion>', lambda event: self.drawMotion(event, 14, 4))
        app[14][5].bind('<Motion>', lambda event: self.drawMotion(event, 14, 5))
        app[14][6].bind('<Motion>', lambda event: self.drawMotion(event, 14, 6))
        app[14][7].bind('<Motion>', lambda event: self.drawMotion(event, 14, 7))
        app[14][8].bind('<Motion>', lambda event: self.drawMotion(event, 14, 8))
        app[14][9].bind('<Motion>', lambda event: self.drawMotion(event, 14, 9))
        app[14][10].bind('<Motion>', lambda event: self.drawMotion(event, 14, 10))
        app[14][11].bind('<Motion>', lambda event: self.drawMotion(event, 14, 11))
        app[14][12].bind('<Motion>', lambda event: self.drawMotion(event, 14, 12))
        app[14][13].bind('<Motion>', lambda event: self.drawMotion(event, 14, 13))
        app[14][14].bind('<Motion>', lambda event: self.drawMotion(event, 14, 14))
        app[14][15].bind('<Motion>', lambda event: self.drawMotion(event, 14, 15))
        app[14][16].bind('<Motion>', lambda event: self.drawMotion(event, 14, 16))
        app[14][17].bind('<Motion>', lambda event: self.drawMotion(event, 14, 17))
        app[14][18].bind('<Motion>', lambda event: self.drawMotion(event, 14, 18))
        app[14][19].bind('<Motion>', lambda event: self.drawMotion(event, 14, 19))
        app[14][20].bind('<Motion>', lambda event: self.drawMotion(event, 14, 20))
        app[14][21].bind('<Motion>', lambda event: self.drawMotion(event, 14, 21))
        app[14][22].bind('<Motion>', lambda event: self.drawMotion(event, 14, 22))
        app[14][23].bind('<Motion>', lambda event: self.drawMotion(event, 14, 23))
        app[14][24].bind('<Motion>', lambda event: self.drawMotion(event, 14, 24))
        app[14][25].bind('<Motion>', lambda event: self.drawMotion(event, 14, 25))
        app[14][26].bind('<Motion>', lambda event: self.drawMotion(event, 14, 26))
        app[14][27].bind('<Motion>', lambda event: self.drawMotion(event, 14, 27))

        app[15][0].bind('<Motion>', lambda event: self.drawMotion(event, 15, 0))
        app[15][1].bind('<Motion>', lambda event: self.drawMotion(event, 15, 1))
        app[15][2].bind('<Motion>', lambda event: self.drawMotion(event, 15, 2))
        app[15][3].bind('<Motion>', lambda event: self.drawMotion(event, 15, 3))
        app[15][4].bind('<Motion>', lambda event: self.drawMotion(event, 15, 4))
        app[15][5].bind('<Motion>', lambda event: self.drawMotion(event, 15, 5))
        app[15][6].bind('<Motion>', lambda event: self.drawMotion(event, 15, 6))
        app[15][7].bind('<Motion>', lambda event: self.drawMotion(event, 15, 7))
        app[15][8].bind('<Motion>', lambda event: self.drawMotion(event, 15, 8))
        app[15][9].bind('<Motion>', lambda event: self.drawMotion(event, 15, 9))
        app[15][10].bind('<Motion>', lambda event: self.drawMotion(event, 15, 10))
        app[15][11].bind('<Motion>', lambda event: self.drawMotion(event, 15, 11))
        app[15][12].bind('<Motion>', lambda event: self.drawMotion(event, 15, 12))
        app[15][13].bind('<Motion>', lambda event: self.drawMotion(event, 15, 13))
        app[15][14].bind('<Motion>', lambda event: self.drawMotion(event, 15, 14))
        app[15][15].bind('<Motion>', lambda event: self.drawMotion(event, 15, 15))
        app[15][16].bind('<Motion>', lambda event: self.drawMotion(event, 15, 16))
        app[15][17].bind('<Motion>', lambda event: self.drawMotion(event, 15, 17))
        app[15][18].bind('<Motion>', lambda event: self.drawMotion(event, 15, 18))
        app[15][19].bind('<Motion>', lambda event: self.drawMotion(event, 15, 19))
        app[15][20].bind('<Motion>', lambda event: self.drawMotion(event, 15, 20))
        app[15][21].bind('<Motion>', lambda event: self.drawMotion(event, 15, 21))
        app[15][22].bind('<Motion>', lambda event: self.drawMotion(event, 15, 22))
        app[15][23].bind('<Motion>', lambda event: self.drawMotion(event, 15, 23))
        app[15][24].bind('<Motion>', lambda event: self.drawMotion(event, 15, 24))
        app[15][25].bind('<Motion>', lambda event: self.drawMotion(event, 15, 25))
        app[15][26].bind('<Motion>', lambda event: self.drawMotion(event, 15, 26))
        app[15][27].bind('<Motion>', lambda event: self.drawMotion(event, 15, 27))

        app[16][0].bind('<Motion>', lambda event: self.drawMotion(event, 16, 0))
        app[16][1].bind('<Motion>', lambda event: self.drawMotion(event, 16, 1))
        app[16][2].bind('<Motion>', lambda event: self.drawMotion(event, 16, 2))
        app[16][3].bind('<Motion>', lambda event: self.drawMotion(event, 16, 3))
        app[16][4].bind('<Motion>', lambda event: self.drawMotion(event, 16, 4))
        app[16][5].bind('<Motion>', lambda event: self.drawMotion(event, 16, 5))
        app[16][6].bind('<Motion>', lambda event: self.drawMotion(event, 16, 6))
        app[16][7].bind('<Motion>', lambda event: self.drawMotion(event, 16, 7))
        app[16][8].bind('<Motion>', lambda event: self.drawMotion(event, 16, 8))
        app[16][9].bind('<Motion>', lambda event: self.drawMotion(event, 16, 9))
        app[16][10].bind('<Motion>', lambda event: self.drawMotion(event, 16, 10))
        app[16][11].bind('<Motion>', lambda event: self.drawMotion(event, 16, 11))
        app[16][12].bind('<Motion>', lambda event: self.drawMotion(event, 16, 12))
        app[16][13].bind('<Motion>', lambda event: self.drawMotion(event, 16, 13))
        app[16][14].bind('<Motion>', lambda event: self.drawMotion(event, 16, 14))
        app[16][15].bind('<Motion>', lambda event: self.drawMotion(event, 16, 15))
        app[16][16].bind('<Motion>', lambda event: self.drawMotion(event, 16, 16))
        app[16][17].bind('<Motion>', lambda event: self.drawMotion(event, 16, 17))
        app[16][18].bind('<Motion>', lambda event: self.drawMotion(event, 16, 18))
        app[16][19].bind('<Motion>', lambda event: self.drawMotion(event, 16, 19))
        app[16][20].bind('<Motion>', lambda event: self.drawMotion(event, 16, 20))
        app[16][21].bind('<Motion>', lambda event: self.drawMotion(event, 16, 21))
        app[16][22].bind('<Motion>', lambda event: self.drawMotion(event, 16, 22))
        app[16][23].bind('<Motion>', lambda event: self.drawMotion(event, 16, 23))
        app[16][24].bind('<Motion>', lambda event: self.drawMotion(event, 16, 24))
        app[16][25].bind('<Motion>', lambda event: self.drawMotion(event, 16, 25))
        app[16][26].bind('<Motion>', lambda event: self.drawMotion(event, 16, 26))
        app[16][27].bind('<Motion>', lambda event: self.drawMotion(event, 16, 27))

        app[17][0].bind('<Motion>', lambda event: self.drawMotion(event, 17, 0))
        app[17][1].bind('<Motion>', lambda event: self.drawMotion(event, 17, 1))
        app[17][2].bind('<Motion>', lambda event: self.drawMotion(event, 17, 2))
        app[17][3].bind('<Motion>', lambda event: self.drawMotion(event, 17, 3))
        app[17][4].bind('<Motion>', lambda event: self.drawMotion(event, 17, 4))
        app[17][5].bind('<Motion>', lambda event: self.drawMotion(event, 17, 5))
        app[17][6].bind('<Motion>', lambda event: self.drawMotion(event, 17, 6))
        app[17][7].bind('<Motion>', lambda event: self.drawMotion(event, 17, 7))
        app[17][8].bind('<Motion>', lambda event: self.drawMotion(event, 17, 8))
        app[17][9].bind('<Motion>', lambda event: self.drawMotion(event, 17, 9))
        app[17][10].bind('<Motion>', lambda event: self.drawMotion(event, 17, 10))
        app[17][11].bind('<Motion>', lambda event: self.drawMotion(event, 17, 11))
        app[17][12].bind('<Motion>', lambda event: self.drawMotion(event, 17, 12))
        app[17][13].bind('<Motion>', lambda event: self.drawMotion(event, 17, 13))
        app[17][14].bind('<Motion>', lambda event: self.drawMotion(event, 17, 14))
        app[17][15].bind('<Motion>', lambda event: self.drawMotion(event, 17, 15))
        app[17][16].bind('<Motion>', lambda event: self.drawMotion(event, 17, 16))
        app[17][17].bind('<Motion>', lambda event: self.drawMotion(event, 17, 17))
        app[17][18].bind('<Motion>', lambda event: self.drawMotion(event, 17, 18))
        app[17][19].bind('<Motion>', lambda event: self.drawMotion(event, 17, 19))
        app[17][20].bind('<Motion>', lambda event: self.drawMotion(event, 17, 20))
        app[17][21].bind('<Motion>', lambda event: self.drawMotion(event, 17, 21))
        app[17][22].bind('<Motion>', lambda event: self.drawMotion(event, 17, 22))
        app[17][23].bind('<Motion>', lambda event: self.drawMotion(event, 17, 23))
        app[17][24].bind('<Motion>', lambda event: self.drawMotion(event, 17, 24))
        app[17][25].bind('<Motion>', lambda event: self.drawMotion(event, 17, 25))
        app[17][26].bind('<Motion>', lambda event: self.drawMotion(event, 17, 26))
        app[17][27].bind('<Motion>', lambda event: self.drawMotion(event, 17, 27))

        app[18][0].bind('<Motion>', lambda event: self.drawMotion(event, 18, 0))
        app[18][1].bind('<Motion>', lambda event: self.drawMotion(event, 18, 1))
        app[18][2].bind('<Motion>', lambda event: self.drawMotion(event, 18, 2))
        app[18][3].bind('<Motion>', lambda event: self.drawMotion(event, 18, 3))
        app[18][4].bind('<Motion>', lambda event: self.drawMotion(event, 18, 4))
        app[18][5].bind('<Motion>', lambda event: self.drawMotion(event, 18, 5))
        app[18][6].bind('<Motion>', lambda event: self.drawMotion(event, 18, 6))
        app[18][7].bind('<Motion>', lambda event: self.drawMotion(event, 18, 7))
        app[18][8].bind('<Motion>', lambda event: self.drawMotion(event, 18, 8))
        app[18][9].bind('<Motion>', lambda event: self.drawMotion(event, 18, 9))
        app[18][10].bind('<Motion>', lambda event: self.drawMotion(event, 18, 10))
        app[18][11].bind('<Motion>', lambda event: self.drawMotion(event, 18, 11))
        app[18][12].bind('<Motion>', lambda event: self.drawMotion(event, 18, 12))
        app[18][13].bind('<Motion>', lambda event: self.drawMotion(event, 18, 13))
        app[18][14].bind('<Motion>', lambda event: self.drawMotion(event, 18, 14))
        app[18][15].bind('<Motion>', lambda event: self.drawMotion(event, 18, 15))
        app[18][16].bind('<Motion>', lambda event: self.drawMotion(event, 18, 16))
        app[18][17].bind('<Motion>', lambda event: self.drawMotion(event, 18, 17))
        app[18][18].bind('<Motion>', lambda event: self.drawMotion(event, 18, 18))
        app[18][19].bind('<Motion>', lambda event: self.drawMotion(event, 18, 19))
        app[18][20].bind('<Motion>', lambda event: self.drawMotion(event, 18, 20))
        app[18][21].bind('<Motion>', lambda event: self.drawMotion(event, 18, 21))
        app[18][22].bind('<Motion>', lambda event: self.drawMotion(event, 18, 22))
        app[18][23].bind('<Motion>', lambda event: self.drawMotion(event, 18, 23))
        app[18][24].bind('<Motion>', lambda event: self.drawMotion(event, 18, 24))
        app[18][25].bind('<Motion>', lambda event: self.drawMotion(event, 18, 25))
        app[18][26].bind('<Motion>', lambda event: self.drawMotion(event, 18, 26))
        app[18][27].bind('<Motion>', lambda event: self.drawMotion(event, 18, 27))

        app[19][0].bind('<Motion>', lambda event: self.drawMotion(event, 19, 0))
        app[19][1].bind('<Motion>', lambda event: self.drawMotion(event, 19, 1))
        app[19][2].bind('<Motion>', lambda event: self.drawMotion(event, 19, 2))
        app[19][3].bind('<Motion>', lambda event: self.drawMotion(event, 19, 3))
        app[19][4].bind('<Motion>', lambda event: self.drawMotion(event, 19, 4))
        app[19][5].bind('<Motion>', lambda event: self.drawMotion(event, 19, 5))
        app[19][6].bind('<Motion>', lambda event: self.drawMotion(event, 19, 6))
        app[19][7].bind('<Motion>', lambda event: self.drawMotion(event, 19, 7))
        app[19][8].bind('<Motion>', lambda event: self.drawMotion(event, 19, 8))
        app[19][9].bind('<Motion>', lambda event: self.drawMotion(event, 19, 9))
        app[19][10].bind('<Motion>', lambda event: self.drawMotion(event, 19, 10))
        app[19][11].bind('<Motion>', lambda event: self.drawMotion(event, 19, 11))
        app[19][12].bind('<Motion>', lambda event: self.drawMotion(event, 19, 12))
        app[19][13].bind('<Motion>', lambda event: self.drawMotion(event, 19, 13))
        app[19][14].bind('<Motion>', lambda event: self.drawMotion(event, 19, 14))
        app[19][15].bind('<Motion>', lambda event: self.drawMotion(event, 19, 15))
        app[19][16].bind('<Motion>', lambda event: self.drawMotion(event, 19, 16))
        app[19][17].bind('<Motion>', lambda event: self.drawMotion(event, 19, 17))
        app[19][18].bind('<Motion>', lambda event: self.drawMotion(event, 19, 18))
        app[19][19].bind('<Motion>', lambda event: self.drawMotion(event, 19, 19))
        app[19][20].bind('<Motion>', lambda event: self.drawMotion(event, 19, 20))
        app[19][21].bind('<Motion>', lambda event: self.drawMotion(event, 19, 21))
        app[19][22].bind('<Motion>', lambda event: self.drawMotion(event, 19, 22))
        app[19][23].bind('<Motion>', lambda event: self.drawMotion(event, 19, 23))
        app[19][24].bind('<Motion>', lambda event: self.drawMotion(event, 19, 24))
        app[19][25].bind('<Motion>', lambda event: self.drawMotion(event, 19, 25))
        app[19][26].bind('<Motion>', lambda event: self.drawMotion(event, 19, 26))
        app[19][27].bind('<Motion>', lambda event: self.drawMotion(event, 19, 27))

        app[20][0].bind('<Motion>', lambda event: self.drawMotion(event, 20, 0))
        app[20][1].bind('<Motion>', lambda event: self.drawMotion(event, 20, 1))
        app[20][2].bind('<Motion>', lambda event: self.drawMotion(event, 20, 2))
        app[20][3].bind('<Motion>', lambda event: self.drawMotion(event, 20, 3))
        app[20][4].bind('<Motion>', lambda event: self.drawMotion(event, 20, 4))
        app[20][5].bind('<Motion>', lambda event: self.drawMotion(event, 20, 5))
        app[20][6].bind('<Motion>', lambda event: self.drawMotion(event, 20, 6))
        app[20][7].bind('<Motion>', lambda event: self.drawMotion(event, 20, 7))
        app[20][8].bind('<Motion>', lambda event: self.drawMotion(event, 20, 8))
        app[20][9].bind('<Motion>', lambda event: self.drawMotion(event, 20, 9))
        app[20][10].bind('<Motion>', lambda event: self.drawMotion(event, 20, 10))
        app[20][11].bind('<Motion>', lambda event: self.drawMotion(event, 20, 11))
        app[20][12].bind('<Motion>', lambda event: self.drawMotion(event, 20, 12))
        app[20][13].bind('<Motion>', lambda event: self.drawMotion(event, 20, 13))
        app[20][14].bind('<Motion>', lambda event: self.drawMotion(event, 20, 14))
        app[20][15].bind('<Motion>', lambda event: self.drawMotion(event, 20, 15))
        app[20][16].bind('<Motion>', lambda event: self.drawMotion(event, 20, 16))
        app[20][17].bind('<Motion>', lambda event: self.drawMotion(event, 20, 17))
        app[20][18].bind('<Motion>', lambda event: self.drawMotion(event, 20, 18))
        app[20][19].bind('<Motion>', lambda event: self.drawMotion(event, 20, 19))
        app[20][20].bind('<Motion>', lambda event: self.drawMotion(event, 20, 20))
        app[20][21].bind('<Motion>', lambda event: self.drawMotion(event, 20, 21))
        app[20][22].bind('<Motion>', lambda event: self.drawMotion(event, 20, 22))
        app[20][23].bind('<Motion>', lambda event: self.drawMotion(event, 20, 23))
        app[20][24].bind('<Motion>', lambda event: self.drawMotion(event, 20, 24))
        app[20][25].bind('<Motion>', lambda event: self.drawMotion(event, 20, 25))
        app[20][26].bind('<Motion>', lambda event: self.drawMotion(event, 20, 26))
        app[20][27].bind('<Motion>', lambda event: self.drawMotion(event, 20, 27))

        app[21][0].bind('<Motion>', lambda event: self.drawMotion(event, 21, 0))
        app[21][1].bind('<Motion>', lambda event: self.drawMotion(event, 21, 1))
        app[21][2].bind('<Motion>', lambda event: self.drawMotion(event, 21, 2))
        app[21][3].bind('<Motion>', lambda event: self.drawMotion(event, 21, 3))
        app[21][4].bind('<Motion>', lambda event: self.drawMotion(event, 21, 4))
        app[21][5].bind('<Motion>', lambda event: self.drawMotion(event, 21, 5))
        app[21][6].bind('<Motion>', lambda event: self.drawMotion(event, 21, 6))
        app[21][7].bind('<Motion>', lambda event: self.drawMotion(event, 21, 7))
        app[21][8].bind('<Motion>', lambda event: self.drawMotion(event, 21, 8))
        app[21][9].bind('<Motion>', lambda event: self.drawMotion(event, 21, 9))
        app[21][10].bind('<Motion>', lambda event: self.drawMotion(event, 21, 10))
        app[21][11].bind('<Motion>', lambda event: self.drawMotion(event, 21, 11))
        app[21][12].bind('<Motion>', lambda event: self.drawMotion(event, 21, 12))
        app[21][13].bind('<Motion>', lambda event: self.drawMotion(event, 21, 13))
        app[21][14].bind('<Motion>', lambda event: self.drawMotion(event, 21, 14))
        app[21][15].bind('<Motion>', lambda event: self.drawMotion(event, 21, 15))
        app[21][16].bind('<Motion>', lambda event: self.drawMotion(event, 21, 16))
        app[21][17].bind('<Motion>', lambda event: self.drawMotion(event, 21, 17))
        app[21][18].bind('<Motion>', lambda event: self.drawMotion(event, 21, 18))
        app[21][19].bind('<Motion>', lambda event: self.drawMotion(event, 21, 19))
        app[21][20].bind('<Motion>', lambda event: self.drawMotion(event, 21, 20))
        app[21][21].bind('<Motion>', lambda event: self.drawMotion(event, 21, 21))
        app[21][22].bind('<Motion>', lambda event: self.drawMotion(event, 21, 22))
        app[21][23].bind('<Motion>', lambda event: self.drawMotion(event, 21, 23))
        app[21][24].bind('<Motion>', lambda event: self.drawMotion(event, 21, 24))
        app[21][25].bind('<Motion>', lambda event: self.drawMotion(event, 21, 25))
        app[21][26].bind('<Motion>', lambda event: self.drawMotion(event, 21, 26))
        app[21][27].bind('<Motion>', lambda event: self.drawMotion(event, 21, 27))

        app[22][0].bind('<Motion>', lambda event: self.drawMotion(event, 22, 0))
        app[22][1].bind('<Motion>', lambda event: self.drawMotion(event, 22, 1))
        app[22][2].bind('<Motion>', lambda event: self.drawMotion(event, 22, 2))
        app[22][3].bind('<Motion>', lambda event: self.drawMotion(event, 22, 3))
        app[22][4].bind('<Motion>', lambda event: self.drawMotion(event, 22, 4))
        app[22][5].bind('<Motion>', lambda event: self.drawMotion(event, 22, 5))
        app[22][6].bind('<Motion>', lambda event: self.drawMotion(event, 22, 6))
        app[22][7].bind('<Motion>', lambda event: self.drawMotion(event, 22, 7))
        app[22][8].bind('<Motion>', lambda event: self.drawMotion(event, 22, 8))
        app[22][9].bind('<Motion>', lambda event: self.drawMotion(event, 22, 9))
        app[22][10].bind('<Motion>', lambda event: self.drawMotion(event, 22, 10))
        app[22][11].bind('<Motion>', lambda event: self.drawMotion(event, 22, 11))
        app[22][12].bind('<Motion>', lambda event: self.drawMotion(event, 22, 12))
        app[22][13].bind('<Motion>', lambda event: self.drawMotion(event, 22, 13))
        app[22][14].bind('<Motion>', lambda event: self.drawMotion(event, 22, 14))
        app[22][15].bind('<Motion>', lambda event: self.drawMotion(event, 22, 15))
        app[22][16].bind('<Motion>', lambda event: self.drawMotion(event, 22, 16))
        app[22][17].bind('<Motion>', lambda event: self.drawMotion(event, 22, 17))
        app[22][18].bind('<Motion>', lambda event: self.drawMotion(event, 22, 18))
        app[22][19].bind('<Motion>', lambda event: self.drawMotion(event, 22, 19))
        app[22][20].bind('<Motion>', lambda event: self.drawMotion(event, 22, 20))
        app[22][21].bind('<Motion>', lambda event: self.drawMotion(event, 22, 21))
        app[22][22].bind('<Motion>', lambda event: self.drawMotion(event, 22, 22))
        app[22][23].bind('<Motion>', lambda event: self.drawMotion(event, 22, 23))
        app[22][24].bind('<Motion>', lambda event: self.drawMotion(event, 22, 24))
        app[22][25].bind('<Motion>', lambda event: self.drawMotion(event, 22, 25))
        app[22][26].bind('<Motion>', lambda event: self.drawMotion(event, 22, 26))
        app[22][27].bind('<Motion>', lambda event: self.drawMotion(event, 22, 27))

        app[23][0].bind('<Motion>', lambda event: self.drawMotion(event, 23, 0))
        app[23][1].bind('<Motion>', lambda event: self.drawMotion(event, 23, 1))
        app[23][2].bind('<Motion>', lambda event: self.drawMotion(event, 23, 2))
        app[23][3].bind('<Motion>', lambda event: self.drawMotion(event, 23, 3))
        app[23][4].bind('<Motion>', lambda event: self.drawMotion(event, 23, 4))
        app[23][5].bind('<Motion>', lambda event: self.drawMotion(event, 23, 5))
        app[23][6].bind('<Motion>', lambda event: self.drawMotion(event, 23, 6))
        app[23][7].bind('<Motion>', lambda event: self.drawMotion(event, 23, 7))
        app[23][8].bind('<Motion>', lambda event: self.drawMotion(event, 23, 8))
        app[23][9].bind('<Motion>', lambda event: self.drawMotion(event, 23, 9))
        app[23][10].bind('<Motion>', lambda event: self.drawMotion(event, 23, 10))
        app[23][11].bind('<Motion>', lambda event: self.drawMotion(event, 23, 11))
        app[23][12].bind('<Motion>', lambda event: self.drawMotion(event, 23, 12))
        app[23][13].bind('<Motion>', lambda event: self.drawMotion(event, 23, 13))
        app[23][14].bind('<Motion>', lambda event: self.drawMotion(event, 23, 14))
        app[23][15].bind('<Motion>', lambda event: self.drawMotion(event, 23, 15))
        app[23][16].bind('<Motion>', lambda event: self.drawMotion(event, 23, 16))
        app[23][17].bind('<Motion>', lambda event: self.drawMotion(event, 23, 17))
        app[23][18].bind('<Motion>', lambda event: self.drawMotion(event, 23, 18))
        app[23][19].bind('<Motion>', lambda event: self.drawMotion(event, 23, 19))
        app[23][20].bind('<Motion>', lambda event: self.drawMotion(event, 23, 20))
        app[23][21].bind('<Motion>', lambda event: self.drawMotion(event, 23, 21))
        app[23][22].bind('<Motion>', lambda event: self.drawMotion(event, 23, 22))
        app[23][23].bind('<Motion>', lambda event: self.drawMotion(event, 23, 23))
        app[23][24].bind('<Motion>', lambda event: self.drawMotion(event, 23, 24))
        app[23][25].bind('<Motion>', lambda event: self.drawMotion(event, 23, 25))
        app[23][26].bind('<Motion>', lambda event: self.drawMotion(event, 23, 26))
        app[23][27].bind('<Motion>', lambda event: self.drawMotion(event, 23, 27))

        app[24][0].bind('<Motion>', lambda event: self.drawMotion(event, 24, 0))
        app[24][1].bind('<Motion>', lambda event: self.drawMotion(event, 24, 1))
        app[24][2].bind('<Motion>', lambda event: self.drawMotion(event, 24, 2))
        app[24][3].bind('<Motion>', lambda event: self.drawMotion(event, 24, 3))
        app[24][4].bind('<Motion>', lambda event: self.drawMotion(event, 24, 4))
        app[24][5].bind('<Motion>', lambda event: self.drawMotion(event, 24, 5))
        app[24][6].bind('<Motion>', lambda event: self.drawMotion(event, 24, 6))
        app[24][7].bind('<Motion>', lambda event: self.drawMotion(event, 24, 7))
        app[24][8].bind('<Motion>', lambda event: self.drawMotion(event, 24, 8))
        app[24][9].bind('<Motion>', lambda event: self.drawMotion(event, 24, 9))
        app[24][10].bind('<Motion>', lambda event: self.drawMotion(event, 24, 10))
        app[24][11].bind('<Motion>', lambda event: self.drawMotion(event, 24, 11))
        app[24][12].bind('<Motion>', lambda event: self.drawMotion(event, 24, 12))
        app[24][13].bind('<Motion>', lambda event: self.drawMotion(event, 24, 13))
        app[24][14].bind('<Motion>', lambda event: self.drawMotion(event, 24, 14))
        app[24][15].bind('<Motion>', lambda event: self.drawMotion(event, 24, 15))
        app[24][16].bind('<Motion>', lambda event: self.drawMotion(event, 24, 16))
        app[24][17].bind('<Motion>', lambda event: self.drawMotion(event, 24, 17))
        app[24][18].bind('<Motion>', lambda event: self.drawMotion(event, 24, 18))
        app[24][19].bind('<Motion>', lambda event: self.drawMotion(event, 24, 19))
        app[24][20].bind('<Motion>', lambda event: self.drawMotion(event, 24, 20))
        app[24][21].bind('<Motion>', lambda event: self.drawMotion(event, 24, 21))
        app[24][22].bind('<Motion>', lambda event: self.drawMotion(event, 24, 22))
        app[24][23].bind('<Motion>', lambda event: self.drawMotion(event, 24, 23))
        app[24][24].bind('<Motion>', lambda event: self.drawMotion(event, 24, 24))
        app[24][25].bind('<Motion>', lambda event: self.drawMotion(event, 24, 25))
        app[24][26].bind('<Motion>', lambda event: self.drawMotion(event, 24, 26))
        app[24][27].bind('<Motion>', lambda event: self.drawMotion(event, 24, 27))

        app[25][0].bind('<Motion>', lambda event: self.drawMotion(event, 25, 0))
        app[25][1].bind('<Motion>', lambda event: self.drawMotion(event, 25, 1))
        app[25][2].bind('<Motion>', lambda event: self.drawMotion(event, 25, 2))
        app[25][3].bind('<Motion>', lambda event: self.drawMotion(event, 25, 3))
        app[25][4].bind('<Motion>', lambda event: self.drawMotion(event, 25, 4))
        app[25][5].bind('<Motion>', lambda event: self.drawMotion(event, 25, 5))
        app[25][6].bind('<Motion>', lambda event: self.drawMotion(event, 25, 6))
        app[25][7].bind('<Motion>', lambda event: self.drawMotion(event, 25, 7))
        app[25][8].bind('<Motion>', lambda event: self.drawMotion(event, 25, 8))
        app[25][9].bind('<Motion>', lambda event: self.drawMotion(event, 25, 9))
        app[25][10].bind('<Motion>', lambda event: self.drawMotion(event, 25, 10))
        app[25][11].bind('<Motion>', lambda event: self.drawMotion(event, 25, 11))
        app[25][12].bind('<Motion>', lambda event: self.drawMotion(event, 25, 12))
        app[25][13].bind('<Motion>', lambda event: self.drawMotion(event, 25, 13))
        app[25][14].bind('<Motion>', lambda event: self.drawMotion(event, 25, 14))
        app[25][15].bind('<Motion>', lambda event: self.drawMotion(event, 25, 15))
        app[25][16].bind('<Motion>', lambda event: self.drawMotion(event, 25, 16))
        app[25][17].bind('<Motion>', lambda event: self.drawMotion(event, 25, 17))
        app[25][18].bind('<Motion>', lambda event: self.drawMotion(event, 25, 18))
        app[25][19].bind('<Motion>', lambda event: self.drawMotion(event, 25, 19))
        app[25][20].bind('<Motion>', lambda event: self.drawMotion(event, 25, 20))
        app[25][21].bind('<Motion>', lambda event: self.drawMotion(event, 25, 21))
        app[25][22].bind('<Motion>', lambda event: self.drawMotion(event, 25, 22))
        app[25][23].bind('<Motion>', lambda event: self.drawMotion(event, 25, 23))
        app[25][24].bind('<Motion>', lambda event: self.drawMotion(event, 25, 24))
        app[25][25].bind('<Motion>', lambda event: self.drawMotion(event, 25, 25))
        app[25][26].bind('<Motion>', lambda event: self.drawMotion(event, 25, 26))
        app[25][27].bind('<Motion>', lambda event: self.drawMotion(event, 25, 27))

        app[26][0].bind('<Motion>', lambda event: self.drawMotion(event, 26, 0))
        app[26][1].bind('<Motion>', lambda event: self.drawMotion(event, 26, 1))
        app[26][2].bind('<Motion>', lambda event: self.drawMotion(event, 26, 2))
        app[26][3].bind('<Motion>', lambda event: self.drawMotion(event, 26, 3))
        app[26][4].bind('<Motion>', lambda event: self.drawMotion(event, 26, 4))
        app[26][5].bind('<Motion>', lambda event: self.drawMotion(event, 26, 5))
        app[26][6].bind('<Motion>', lambda event: self.drawMotion(event, 26, 6))
        app[26][7].bind('<Motion>', lambda event: self.drawMotion(event, 26, 7))
        app[26][8].bind('<Motion>', lambda event: self.drawMotion(event, 26, 8))
        app[26][9].bind('<Motion>', lambda event: self.drawMotion(event, 26, 9))
        app[26][10].bind('<Motion>', lambda event: self.drawMotion(event, 26, 10))
        app[26][11].bind('<Motion>', lambda event: self.drawMotion(event, 26, 11))
        app[26][12].bind('<Motion>', lambda event: self.drawMotion(event, 26, 12))
        app[26][13].bind('<Motion>', lambda event: self.drawMotion(event, 26, 13))
        app[26][14].bind('<Motion>', lambda event: self.drawMotion(event, 26, 14))
        app[26][15].bind('<Motion>', lambda event: self.drawMotion(event, 26, 15))
        app[26][16].bind('<Motion>', lambda event: self.drawMotion(event, 26, 16))
        app[26][17].bind('<Motion>', lambda event: self.drawMotion(event, 26, 17))
        app[26][18].bind('<Motion>', lambda event: self.drawMotion(event, 26, 18))
        app[26][19].bind('<Motion>', lambda event: self.drawMotion(event, 26, 19))
        app[26][20].bind('<Motion>', lambda event: self.drawMotion(event, 26, 20))
        app[26][21].bind('<Motion>', lambda event: self.drawMotion(event, 26, 21))
        app[26][22].bind('<Motion>', lambda event: self.drawMotion(event, 26, 22))
        app[26][23].bind('<Motion>', lambda event: self.drawMotion(event, 26, 23))
        app[26][24].bind('<Motion>', lambda event: self.drawMotion(event, 26, 24))
        app[26][25].bind('<Motion>', lambda event: self.drawMotion(event, 26, 25))
        app[26][26].bind('<Motion>', lambda event: self.drawMotion(event, 26, 26))
        app[26][27].bind('<Motion>', lambda event: self.drawMotion(event, 26, 27))

        app[27][0].bind('<Motion>', lambda event: self.drawMotion(event, 27, 0))
        app[27][1].bind('<Motion>', lambda event: self.drawMotion(event, 27, 1))
        app[27][2].bind('<Motion>', lambda event: self.drawMotion(event, 27, 2))
        app[27][3].bind('<Motion>', lambda event: self.drawMotion(event, 27, 3))
        app[27][4].bind('<Motion>', lambda event: self.drawMotion(event, 27, 4))
        app[27][5].bind('<Motion>', lambda event: self.drawMotion(event, 27, 5))
        app[27][6].bind('<Motion>', lambda event: self.drawMotion(event, 27, 6))
        app[27][7].bind('<Motion>', lambda event: self.drawMotion(event, 27, 7))
        app[27][8].bind('<Motion>', lambda event: self.drawMotion(event, 27, 8))
        app[27][9].bind('<Motion>', lambda event: self.drawMotion(event, 27, 9))
        app[27][10].bind('<Motion>', lambda event: self.drawMotion(event, 27, 10))
        app[27][11].bind('<Motion>', lambda event: self.drawMotion(event, 27, 11))
        app[27][12].bind('<Motion>', lambda event: self.drawMotion(event, 27, 12))
        app[27][13].bind('<Motion>', lambda event: self.drawMotion(event, 27, 13))
        app[27][14].bind('<Motion>', lambda event: self.drawMotion(event, 27, 14))
        app[27][15].bind('<Motion>', lambda event: self.drawMotion(event, 27, 15))
        app[27][16].bind('<Motion>', lambda event: self.drawMotion(event, 27, 16))
        app[27][17].bind('<Motion>', lambda event: self.drawMotion(event, 27, 17))
        app[27][18].bind('<Motion>', lambda event: self.drawMotion(event, 27, 18))
        app[27][19].bind('<Motion>', lambda event: self.drawMotion(event, 27, 19))
        app[27][20].bind('<Motion>', lambda event: self.drawMotion(event, 27, 20))
        app[27][21].bind('<Motion>', lambda event: self.drawMotion(event, 27, 21))
        app[27][22].bind('<Motion>', lambda event: self.drawMotion(event, 27, 22))
        app[27][23].bind('<Motion>', lambda event: self.drawMotion(event, 27, 23))
        app[27][24].bind('<Motion>', lambda event: self.drawMotion(event, 27, 24))
        app[27][25].bind('<Motion>', lambda event: self.drawMotion(event, 27, 25))
        app[27][26].bind('<Motion>', lambda event: self.drawMotion(event, 27, 26))
        app[27][27].bind('<Motion>', lambda event: self.drawMotion(event, 27, 27))

        root.mainloop()
    def draw(self, event):

        global buttonPress, buttonRelease, app
        if str(event.type) == 'ButtonPress':
            buttonPress = True
            buttonRelease = False

    def drawMotion(self, event, i, j):

        global buttonPress, buttonRelease, app
        if (str(event.type) == "Motion"):
            if (buttonPress == True):
                if (event.x > 25):
                    j += int(event.x / 25)
                    if j > 27:
                        j = 27
                elif (event.x < 0):
                    j -= int((-event.x / 25))
                    j -= 1
                    if j < 0:
                        j = 0
                if (event.y > 25):
                    i += int(event.y / 25)
                    if i > 27:
                        i = 27
                elif (event.y < 0):
                    i -= int((-event.y / 25))
                    i -= 1
                    if i < 0:
                        i = 0
                app[i][j].configure(bg='#FFF')
                try:
                    if i != 0:
                        if app[i - 1][j]["bg"] != "#FFF":
                            app[i - 1][j].configure(bg='#808080')
                except:
                    pass
                try:
                    if app[i][j + 1]["bg"] != "#FFF":
                        app[i][j + 1].configure(bg='#808080')
                except:
                    pass
                try:
                    if j != 0:
                        if app[i][j - 1]["bg"] != "#FFF":
                            app[i][j - 1].configure(bg='#808080')
                except:
                    pass
                try:
                    if app[i + 1][j]["bg"] != "#FFF":
                        app[i + 1][j].configure(bg='#808080')
                except:
                    pass

    def endDraw(self, event, root):

        global buttonPress, buttonRelease, app, testArray
        if (str(event.type) == "ButtonRelease"):
            buttonRelease = True
            buttonPress = False
            for i in range(28):
                for j in range(28):
                    if app[i][j]["bg"] == "#000":
                        testArray[i][j] = 0
                    elif app[i][j]["bg"] == "#FFF":
                        testArray[i][j] = 1
                    else:
                        testArray[i][j] = 0.5


    def clearBoard(self, app):

        for i in range(28):
            for j in range(28):
                app[i][j - 1].configure(bg='#000')

    def showPredictedNo(self, predictedNo):

        ans = [[1 for j in range(28)] for i in range(28)]
        root = Tk()
        root.title('Number Predictor')
        for i in range(28):
            for j in range(28):
                if testArray[i][j] == 0:
                    ans[i][j] = Label(root, text="", bg='#FFF', font=('Verdana', 12), width=2, height=1)
                elif testArray[i][j] == 1:
                    ans[i][j] = Label(root, text="", bg='#000', font=('Verdana', 12), width=2, height=1)
                else:
                    ans[i][j] = Label(root, text="", bg='#808080', font=('Verdana', 12), width=2, height=1)

                ans[i][j].grid(row=i, column=j, padx=0, pady=0, columnspan=1)

        messagebox.showinfo("Prediction", "Predicted Number = "+str(predictedNo))
        root.destroy()


if __name__ == "__main__":
    print("Shows Board to Draw a Number")
else:
    print("drawNumber is successfully imported")